name: "node-docker-build-action"
description: "Build a GB node app (yarn+TS based) and Pushes built artifacts to a container registry"

inputs:
  npm-token:
    description: "npm credentials, most useful for private repositories"
    required: true
  image-tag:
    description: "The desired tag for the Docker image"
    required: false
    default: ${{ github.run_id }}_${{ github.sha }}
  registry-name:
    description: "The name of the ECR registry repository"
    required: true
  aws-access-key-id:
    description: "AWS account id for image registry"
    required: true
  aws-secret-access-key:
    description: "AWS Secret for the access key"
    required: true
  aws-region:
    description: "AWS region for the image registry"
    required: false
    default: us-east-1
  skip-build:
    description: "Set to true if the Docker image is already built earlier in the workflow"
    required: false
    default: false
  repo-org:
    description: "The organization to setup for private package installation"
    required: false
    default: gasbuddy

runs:
  using: "composite"
  steps:
    - name: Build docker image ${{ inputs.registry-name }}:${{ inputs.image-tag }}
      shell: bash
      run: |
        cp ${{ github.action_path }}/Dockerfile .
        touch static
        touch migrations
        echo "config/development.json" >> .dockerignore
        echo "config/test.json" >> .dockerignore
        docker build --build-arg REPO_ORG=${{ inputs.repo-org }} --build-arg NPM_TOKEN=${{ inputs.npm-token }} -t ${{ inputs.registry-name }}:${{ inputs.image-tag }} .
      if: ${{ inputs.skip-build != 'true' }}

    - name: Push to ECR
      id: ecr
      uses: gas-buddy/gh-ecr-push@v1.3.6
      with:
        access-key-id: ${{ inputs.aws-access-key-id }}
        secret-access-key: ${{ inputs.aws-secret-access-key }}
        region: ${{ inputs.aws-region }}
        image: ${{ inputs.registry-name }}:${{ inputs.image-tag }}